Adds missing algorithm include
Before this change compilation failed with:

```cmake
src/fileshelter/ui/ShareCreateFormView.cpp:285:29: error: ‘count_if’ is not a member of ‘std’
  285 |                 return std::count_if(std::cbegin(files), std::cend(files),
```